### ISSUE TITLE
Is it possible to add the sveltekit specific attribute to an "a" button ?

### ISSUE THREAD

**Issue by MichaelBailly** [novacbn/kahi-ui#100]
### Describe the Question

Hello,

I'm looking for how to add the property `sveltekit:prefetch` to a button with an href. The doc is here https://kit.svelte.dev/docs#anchor-options-sveltekit-prefetch .

```
<Button href="/mysite/page2"></Button>
```
How can I tell Kahi to add the sceltekit:prefetch attribute?

**Comment by novacbn** [comment]
Sorry, I should document that! The framework already supports that on all link Components. Did a quick test a [Playground REPL](https://kahi-ui.nbn.dev/playground/?script=PHNjcmlwdD4KICAgIGltcG9ydCB7QW5jaG9yLCBCdXR0b259IGZyb20gIkBrYWhpLXVpL2ZyYW1ld29yayI7CjwvyEEKPMY3xUpocmVmPSIvZG9jcy9pbnRlcmFjdGFibGVzL2LFVCLFJnN2ZWx0ZWtpdDpub3Njcm9sbM8XcHJlZmV0Y2gK5gCgR290b%2BcAlQo8L8ZvxHliciAvxAjHG%2F8Agf8Agf8AgesAgcYJPg%3D%3D), seems to be rendering to DOM fine with those attributes. So I believe they should work.

![button-anchor-sveltekit-attributes](https://user-images.githubusercontent.com/31122674/146707792-3da64e19-cbda-4c38-aa43-3199fed99cf9.png)

Let me know if it doesn't actually function properly.

**Comment by MichaelBailly** [comment]
I confirm, that works! Thank you.
