### ISSUE TITLE
Feature request: Calendar, date/time  widget

### ISSUE THREAD

**Issue by jvijay-work** [novacbn/kahi-ui#16]
How about adding a Calendar + date and time widget?

**Comment by novacbn** [comment]
Right now I'm focusing on primitive Components and improving developer experience. But Picker components are planned for the future.

**Comment by novacbn** [comment]
Extremely late, but better late than never! Anyway the widgets are more or less done and will be coming out later in `0.4.10` sometime this week.

You can see the current iterations below:

- [TimePicker](https://novacbn-kahi-ui-pr-81-run-350.surge.sh/?path=/story/widgets-timepicker--default)
- [DayPicker](https://novacbn-kahi-ui-pr-81-run-350.surge.sh/?path=/story/widgets-daypicker--default)
- [MonthPicker](https://novacbn-kahi-ui-pr-81-run-350.surge.sh/?path=/story/widgets-monthpicker--default)
- [YearPicker](https://novacbn-kahi-ui-pr-81-run-350.surge.sh/?path=/story/widgets-yearpicker--default)
- [DayStepper](https://novacbn-kahi-ui-pr-81-run-350.surge.sh/?path=/story/widgets-daystepper--default)
- [MonthStepper](https://novacbn-kahi-ui-pr-81-run-350.surge.sh/?path=/story/widgets-monthstepper--default)
- [YearStepper](https://novacbn-kahi-ui-pr-81-run-350.surge.sh/?path=/story/widgets-yearstepper--default)

Those are just the primitive self-contained widgets, not the form inputs with SSR fallback. That will come in future update. Let me know if there's any feature you think that might be missing that you require.

**Comment by novacbn** [comment]
Closed due to inactivity.
