### ISSUE TITLE
<Stack orientation="horizontal"> does not work

### ISSUE THREAD

**Issue by samuelstroschein** [novacbn/kahi-ui#23]
```Svelte
<script>
	import { Stack } from '@kahi-ui/framework';
</script>


<Stack orientation="horizontal">
  <p>HI</p>
  <p>HOW ARE YOU</p>
  <p>?</p>
</Stack>

```
<img width="185" alt="Screenshot 2021-08-07 at 15 18 35" src="https://user-images.githubusercontent.com/35429197/128601565-7be883c5-6c07-4fb5-b5ac-1949387f0938.png">

**Comment by novacbn** [comment]
I tested it in an application, the REPL, and the starter template. Seems to work fine.

Do you have the CSS loaded in your application via HTML or imports like [described here](https://kahi-ui.nbn.dev/docs/framework/getting-started/#importing-stylesheet)?

![#23-stack-does-not-work](https://user-images.githubusercontent.com/31122674/128618096-af0120fd-c843-4a83-972a-bf288ba8fa7a.png)

**Comment by samuelstroschein** [comment]
Now that you ask, I am unsure. I did place the snippet in the root `app.html` file from SvelteKit when I first installed Kahi but I might have removed it before I tested the Stack component. Since it's working in the starter template, I assume I did in fact remove the CSS and will therefore close the issue.
