### ISSUE TITLE
[REQUEST] Datatable component

### ISSUE THREAD

**Issue by ragokan** [novacbn/kahi-ui#98]
### Describe the Request

I loved the components of Kahi UI and there are so many amazing components. I would like to see a datatable component just like some other libraries do have. Example;
https://smeltejs.com/components/data-tables

**Comment by novacbn** [comment]
Sure, I'll take a crack at it after I get `0.5.0` or so out and released.

**Comment by ragokan** [comment]
> Sure, I'll take a crack at it after I get `0.5.0` or so out and released.

Amazing, thank you!

**Comment by novacbn** [comment]
Hi! Sorry for the delay, but I believe I got most of features common to `DataTable` Components. 

> current in-dev: https://novacbn-kahi-ui-pr-112-run-635.surge.sh/?path=/story/widgets-datatable--preview

- Input collection, output table.
- Pagination
- Filtering + Customization
- Sorting + Customiation
- Custom Slots

Is there anything else required in features before I push the release?

**Comment by ragokan** [comment]
> 

Wow, no thank you. It is amazing.

**Comment by novacbn** [comment]
Alright, it should be live in `0.5.3`. You can [check out the documentation here](https://kahi-ui.nbn.dev/docs/widgets/datatable). Let me know if you run into usage troubles.
